//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "address_scopes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub project_id: Option<String>,
    pub shared: i8,
    pub ip_version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::addressscoperbacs::Entity")]
    Addressscoperbacs,
}

impl Related<super::addressscoperbacs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addressscoperbacs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
