//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "addressscoperbacs")]
pub struct Model {
    pub project_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub target_project: String,
    pub action: String,
    pub object_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::address_scopes::Entity",
        from = "Column::ObjectId",
        to = "super::address_scopes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    AddressScopes,
}

impl Related<super::address_scopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AddressScopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
