//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "address_groups")]
pub struct Model {
    pub project_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub standard_attr_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::address_associations::Entity")]
    AddressAssociations,
    #[sea_orm(has_many = "super::addressgrouprbacs::Entity")]
    Addressgrouprbacs,
    #[sea_orm(has_many = "super::securitygrouprules::Entity")]
    Securitygrouprules,
    #[sea_orm(
        belongs_to = "super::standardattributes::Entity",
        from = "Column::StandardAttrId",
        to = "super::standardattributes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Standardattributes,
}

impl Related<super::address_associations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AddressAssociations.def()
    }
}

impl Related<super::addressgrouprbacs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Addressgrouprbacs.def()
    }
}

impl Related<super::securitygrouprules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Securitygrouprules.def()
    }
}

impl Related<super::standardattributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Standardattributes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
