//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bgp_speaker_network_bindings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub bgp_speaker_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub network_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ip_version: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bgp_speakers::Entity",
        from = "Column::BgpSpeakerId",
        to = "super::bgp_speakers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BgpSpeakers,
    #[sea_orm(
        belongs_to = "super::networks::Entity",
        from = "Column::NetworkId",
        to = "super::networks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Networks,
}

impl Related<super::bgp_speakers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BgpSpeakers.def()
    }
}

impl Related<super::networks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
