//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bgp_peers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub auth_type: String,
    pub password: Option<String>,
    pub peer_ip: String,
    pub remote_as: i32,
    pub tenant_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bgp_speaker_peer_bindings::Entity")]
    BgpSpeakerPeerBindings,
}

impl Related<super::bgp_speaker_peer_bindings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BgpSpeakerPeerBindings.def()
    }
}

impl Related<super::bgp_speakers::Entity> for Entity {
    fn to() -> RelationDef {
        super::bgp_speaker_peer_bindings::Relation::BgpSpeakers.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::bgp_speaker_peer_bindings::Relation::BgpPeers
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
