//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "firewalls")]
pub struct Model {
    pub tenant_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    pub description: Option<String>,
    pub shared: Option<i8>,
    pub admin_state_up: Option<i8>,
    pub status: Option<String>,
    pub firewall_policy_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::firewall_policies::Entity",
        from = "Column::FirewallPolicyId",
        to = "super::firewall_policies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FirewallPolicies,
}

impl Related<super::firewall_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FirewallPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
