//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "flavorserviceprofilebindings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub service_profile_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub flavor_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flavors::Entity",
        from = "Column::FlavorId",
        to = "super::flavors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Flavors,
    #[sea_orm(
        belongs_to = "super::serviceprofiles::Entity",
        from = "Column::ServiceProfileId",
        to = "super::serviceprofiles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Serviceprofiles,
}

impl Related<super::flavors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flavors.def()
    }
}

impl Related<super::serviceprofiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Serviceprofiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
