//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "floatingipdnses")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub floatingip_id: String,
    pub dns_name: String,
    pub dns_domain: String,
    pub published_dns_name: String,
    pub published_dns_domain: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::floatingips::Entity",
        from = "Column::FloatingipId",
        to = "super::floatingips::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Floatingips,
}

impl Related<super::floatingips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Floatingips.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
