//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ipallocationpools")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub subnet_id: Option<String>,
    pub first_ip: String,
    pub last_ip: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subnets::Entity",
        from = "Column::SubnetId",
        to = "super::subnets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subnets,
}

impl Related<super::subnets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subnets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
