//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ipamsubnets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub neutron_subnet_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ipamallocationpools::Entity")]
    Ipamallocationpools,
    #[sea_orm(has_many = "super::ipamallocations::Entity")]
    Ipamallocations,
}

impl Related<super::ipamallocationpools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ipamallocationpools.def()
    }
}

impl Related<super::ipamallocations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ipamallocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
