//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ipamallocationpools")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub ipam_subnet_id: String,
    pub first_ip: String,
    pub last_ip: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ipamsubnets::Entity",
        from = "Column::IpamSubnetId",
        to = "super::ipamsubnets::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Ipamsubnets,
}

impl Related<super::ipamsubnets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ipamsubnets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
