//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ipsecpeercidrs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cidr: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub ipsec_site_connection_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ipsec_site_connections::Entity",
        from = "Column::IpsecSiteConnectionId",
        to = "super::ipsec_site_connections::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    IpsecSiteConnections,
}

impl Related<super::ipsec_site_connections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IpsecSiteConnections.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
