//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "local_ips")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub standard_attr_id: i64,
    pub name: Option<String>,
    pub project_id: Option<String>,
    pub local_port_id: String,
    pub network_id: String,
    pub local_ip_address: String,
    pub ip_mode: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::local_ip_associations::Entity")]
    LocalIpAssociations,
    #[sea_orm(
        belongs_to = "super::ports::Entity",
        from = "Column::LocalPortId",
        to = "super::ports::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Ports,
    #[sea_orm(
        belongs_to = "super::standardattributes::Entity",
        from = "Column::StandardAttrId",
        to = "super::standardattributes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Standardattributes,
}

impl Related<super::local_ip_associations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LocalIpAssociations.def()
    }
}

impl Related<super::standardattributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Standardattributes.def()
    }
}

impl Related<super::ports::Entity> for Entity {
    fn to() -> RelationDef {
        super::local_ip_associations::Relation::Ports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::local_ip_associations::Relation::LocalIps.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
