//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "members")]
pub struct Model {
    pub tenant_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub status: String,
    pub status_description: Option<String>,
    pub pool_id: String,
    pub address: String,
    pub protocol_port: i32,
    pub weight: i32,
    pub admin_state_up: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pools::Entity",
        from = "Column::PoolId",
        to = "super::pools::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pools,
}

impl Related<super::pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
