//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "meteringlabels")]
pub struct Model {
    pub project_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    pub description: Option<String>,
    pub shared: Option<i8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::meteringlabelrules::Entity")]
    Meteringlabelrules,
}

impl Related<super::meteringlabelrules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meteringlabelrules.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
