//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ml2_port_binding_levels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub port_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub host: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub level: i32,
    pub driver: Option<String>,
    pub segment_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::networksegments::Entity",
        from = "Column::SegmentId",
        to = "super::networksegments::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Networksegments,
    #[sea_orm(
        belongs_to = "super::ports::Entity",
        from = "Column::PortId",
        to = "super::ports::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Ports,
}

impl Related<super::networksegments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networksegments.def()
    }
}

impl Related<super::ports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ports.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
