//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ovn_revision_numbers")]
pub struct Model {
    pub standard_attr_id: Option<i64>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_uuid: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource_type: String,
    pub revision_number: i64,
    pub created_at: DateTime,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::standardattributes::Entity",
        from = "Column::StandardAttrId",
        to = "super::standardattributes::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Standardattributes,
}

impl Related<super::standardattributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Standardattributes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
