//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "poolstatisticss")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub pool_id: String,
    pub bytes_in: i64,
    pub bytes_out: i64,
    pub active_connections: i64,
    pub total_connections: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pools::Entity",
        from = "Column::PoolId",
        to = "super::pools::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pools,
}

impl Related<super::pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
