//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "poolmonitorassociations")]
pub struct Model {
    pub status: String,
    pub status_description: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub pool_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub monitor_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::healthmonitors::Entity",
        from = "Column::MonitorId",
        to = "super::healthmonitors::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Healthmonitors,
    #[sea_orm(
        belongs_to = "super::pools::Entity",
        from = "Column::PoolId",
        to = "super::pools::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Pools,
}

impl Related<super::healthmonitors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Healthmonitors.def()
    }
}

impl Related<super::pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
