//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "providerresourceassociations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub provider_name: String,
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub resource_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
