//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use super::sea_orm_active_enums::Direction;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "qos_packet_rate_limit_rules")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub qos_policy_id: String,
    pub max_kpps: Option<i32>,
    pub max_burst_kpps: Option<i32>,
    pub direction: Direction,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::qos_policies::Entity",
        from = "Column::QosPolicyId",
        to = "super::qos_policies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    QosPolicies,
}

impl Related<super::qos_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QosPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
