//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "qos_fip_policy_bindings")]
pub struct Model {
    pub policy_id: String,
    #[sea_orm(primary_key)]
    pub fip_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::floatingips::Entity",
        from = "Column::FipId",
        to = "super::floatingips::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Floatingips,
    #[sea_orm(
        belongs_to = "super::qos_policies::Entity",
        from = "Column::PolicyId",
        to = "super::qos_policies::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    QosPolicies,
}

impl Related<super::floatingips::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Floatingips.def()
    }
}

impl Related<super::qos_policies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QosPolicies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
