//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "resourcedeltas")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub resource: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub reservation_id: String,
    pub amount: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::reservations::Entity",
        from = "Column::ReservationId",
        to = "super::reservations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Reservations,
}

impl Related<super::reservations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Reservations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
