//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "routerrules")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub source: String,
    pub destination: String,
    pub action: String,
    pub router_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::nexthops::Entity")]
    Nexthops,
    #[sea_orm(
        belongs_to = "super::routers::Entity",
        from = "Column::RouterId",
        to = "super::routers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Routers,
}

impl Related<super::nexthops::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nexthops.def()
    }
}

impl Related<super::routers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Routers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
