//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "securitygroups")]
pub struct Model {
    pub project_id: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: Option<String>,
    #[sea_orm(unique)]
    pub standard_attr_id: i64,
    pub stateful: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::default_security_group::Entity")]
    DefaultSecurityGroup,
    #[sea_orm(has_many = "super::securitygroupportbindings::Entity")]
    Securitygroupportbindings,
    #[sea_orm(has_many = "super::securitygrouprbacs::Entity")]
    Securitygrouprbacs,
    #[sea_orm(
        belongs_to = "super::standardattributes::Entity",
        from = "Column::StandardAttrId",
        to = "super::standardattributes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Standardattributes,
}

impl Related<super::default_security_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DefaultSecurityGroup.def()
    }
}

impl Related<super::securitygroupportbindings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Securitygroupportbindings.def()
    }
}

impl Related<super::securitygrouprbacs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Securitygrouprbacs.def()
    }
}

impl Related<super::standardattributes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Standardattributes.def()
    }
}

impl Related<super::ports::Entity> for Entity {
    fn to() -> RelationDef {
        super::securitygroupportbindings::Relation::Ports.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::securitygroupportbindings::Relation::Securitygroups
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
