//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "segmenthostmappings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub segment_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub host: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::networksegments::Entity",
        from = "Column::SegmentId",
        to = "super::networksegments::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Networksegments,
}

impl Related<super::networksegments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Networksegments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
