//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subnetpoolprefixes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cidr: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subnetpool_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::subnetpools::Entity",
        from = "Column::SubnetpoolId",
        to = "super::subnetpools::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Subnetpools,
}

impl Related<super::subnetpools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subnetpools.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
