//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub port_id: String,
    pub trunk_id: String,
    pub segmentation_type: String,
    pub segmentation_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ports::Entity",
        from = "Column::PortId",
        to = "super::ports::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Ports,
    #[sea_orm(
        belongs_to = "super::trunks::Entity",
        from = "Column::TrunkId",
        to = "super::trunks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Trunks,
}

impl Related<super::ports::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ports.def()
    }
}

impl Related<super::trunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trunks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
